amplify.yml.txt
=> added amplify text for deploy

package.json
=> added reactQueryDev

client/package-lock.json, package-lock.json
=> deleted Client, reran npm i

package-lock.json, package.json
=> fresh start

package-lock.json
=> pack json and pack lock sync

src/components/search/index.js
=> fixed build issue

src/App.js, src/components/search/index.js
- [X ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ X] Complete, but not tested (may need new tests)
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] My changes generate no new warnings
- [ X] There are no merge conflicts
=> Models are dependent on Makes now

package-lock.json, package.json, src/App.js, src/components/results/index.js, src/components/search/index.js, src/index.js
=> Submit button renders car component

src/App.js, src/components/buttons/submitSingleCarResults.js, src/components/dropdown/index.js, src/components/results/index.js, src/components/search/index.js, src/components/singleCarSearch/index.js, src/hooks/dataFetching.js, src/index.js
Co-Authored-by: b-dubz79 <bwardwell79@gmail.com>
Co-Authored-by: Issac909 <issaxavier909@gmail.com>
=> Year Dropdown

src/App.js, src/components/buttons/singleCarSearch/index.js, src/components/buttons/singleCarSearch/modal.js, src/components/dropdown/index.js, src/components/results/index.js, src/components/search/index.js, src/hooks/dataFetching.js, src/hooks/dropdownFunctions.js
=> Added dropdown sub menu

src/App.js, src/components/search/index.js, src/hooks/dropdownFunctions.js
=> Optimized search with sub-model

src/components/details/index.js, src/hooks/dataFetching.js
Instead of hard coding a value, fetch the prediction from the server.
=> Fetch CO2 emissions prediction for gauge

src/App.js, src/AppStyle.jsx, src/components/details/index.js, src/components/details/styles.jsx, src/components/search/styles.jsx
=> Styling: Landing

src/AppStyle.jsx, src/components/details/index.js, src/components/details/styles.jsx, src/components/dropdown/index.js, src/components/dropdown/styles.jsx, src/components/results/index.js, src/components/results/styles.jsx, src/components/search/index.js
Added Cost to Own to car details page
Changed Selection to Dropdown across the code
=> Cost to Own, renaming Dropdown

src/components/details/index.js, src/hooks/dataFetching.js
This fixes the cost of ownership not showing up
=> Update price fetch to use `/api/predict`

package-lock.json, package.json, src/components/details/index.js, src/components/gauge/index.js
Before:
After:
(Ignore the cost of ownership being fixed, that's fixed in #43 )
=> Copy and modify linear guage

src/components/details/index.js, src/components/details/styles.jsx, src/components/gauge/index.js
=> Make the gauge more responsive to CSS

package-lock.json, src/AppStyle.jsx, src/components/home-results/index.js, src/components/home-results/styles.jsx, src/components/home/index.js, src/components/home/styles.jsx, src/components/search/index.js
Fix: Made search result cards responsive with more visually satisfying styling.
Bug: Still need to fix the results rendering within the hero, which pushes everything down upon return
=> Responsive search result cards

src/components/details/index.js, src/components/details/styles.jsx, src/components/gauge/index.js, src/components/image-gallery/index.js
Fix: Spread of info, all text data on the left side so there is room for the image gallery
=> Car Details page

.github/workflows/ci.yml
This will make cypress run on every new commit pushed to github.
=> Add cypress continuous integration

src/components/home/index.js
=> a better solution

src/AppStyle.jsx, src/components/5-year-cost/index.js, src/components/app-content/index.js, src/components/compare-start/index.js, src/components/compare/index.js, src/components/details/styles.jsx, src/components/dropdown/styles.jsx, src/components/home/index.js, src/components/home/styles.jsx, src/components/image-gallery/index.js, src/components/results/compare-results/index.js, src/components/results/home-results/index.js, src/components/results/home-results/styles.jsx, src/components/search/compare-search/index.js, src/components/search/home-search/index.js, src/hooks/dataFetching.js, src/hooks/pageTransitions.js
- [X ] New feature (non-breaking change which adds functionality)
- [X ] Complete, but not tested (may need new tests)
- [ X] I have performed a self-review of my own code
- [X ] My code has been reviewed by at least one peer
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] There are no merge conflicts
=> Everything is hardcoded, user can compare

src/AppStyle.jsx, src/components/common/breakdown/index.js, src/components/compare/index.js, src/components/compare/styles.jsx, src/components/details/index.js, src/constants.js
Makes the compare page look nicer
No tests have been added for this change.
=> Style compare page

src/components/compare/index.js, src/components/compare/styles.jsx
=> Fix images on compare page for chrome
